name: "Build And Release"

on:
  push:
    branches:
      - master

jobs:
  build_for_windows:
    name: "Build for Windows"
    runs-on: [windows-2022]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
          
      # - name: "Install CUDA"
      #   shell: powershell
      #   run: |
      #     choco install cuda --version=12.0.1.52833 -y
      #     "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin" >> $env:GITHUB_PATH

      - name: "Build"
        shell: cmd
        run: |
          cl.exe /c /I"${{ github.workspace }}\Curl\include" /I"${{ github.workspace }}\OpenCL\include" /Zi /nologo /W1 /WX- /diagnostics:column /O2 /D BUILDING_LIBCURL /D HTTP_ONLY /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"${{ github.workspace }}\dist\\" /Fe"${{ github.workspace }}\dist\\" /external:W1 /Gd /TP /FC /errorReport:prompt Dispatcher.cpp Mode.cpp precomp.cpp profanity.cpp SpeedSample.cpp
          link.exe /ERRORREPORT:PROMPT /OUT:"${{ github.workspace }}\dist\profanity.exe" /NOLOGO /LIBPATH:"${{ github.workspace }}\Curl\lib" /LIBPATH:"${{ github.workspace }}\OpenCL\lib" OpenCL.lib libcurl_a.lib ws2_32.lib winmm.lib wldap32.lib crypt32.lib normaliz.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"${{ github.workspace }}\dist\profanity.pdb" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"${{ github.workspace }}\dist\profanity.lib" /MACHINE:X64 "${{ github.workspace }}\dist\*.obj"

      - name: "Build Result"
        run: dir ${{ github.workspace }}/dist/*.*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/dist/profanity.exe,${{ github.workspace }}/dist/README.md,${{ github.workspace }}/dist/start.bat,${{ github.workspace }}/profanity.txt"
          tag: v1.1.0
          draft: true
          allowUpdates: true
          replacesArtifacts: false
